### ISSUE TITLE
Question about milight proxy

### ISSUE THREAD

**Issue by nbittmann** [cognitivegears/pilumen#1]
Hi there,

First of all thank you for your work on this however a few questions came into my mind about this:
1. If I convert my bridge with this does it allow me to pair new bulbs ? If yes any special steps necessary?
2. Will this allow me to run more than 4 Groups of lights essentially extend the functionality of my bridge?

Thanks

**Comment by cognitivegears** [comment]
Hi nbittmann,

Yes, you can still pair new bulbs with this.  You turn on a group when giving power to the bulb, same as without the proxy.  Unfortunately it doesn't change the limit on groups.

Best of luck!
